development:
  adapter: postgresql
  database: crusher
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: crusher
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: crusher
  pool: 5
  timeout: 5000